# This file specifies how to fund development of this project
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# You can add your sponsorship platform here
# github: [username]  # GitHub Sponsors
# patreon: username   # Patreon
# open_collective: username  # Open Collective
# ko_fi: username     # Ko-fi
# tidelift: "package/npm/package-name"  # Tidelift
# community_bridge: project-name  # Community Bridge
# liberapay: username  # Liberapay
# issuehunt: username  # IssueHunt
# otechie: username    # Otechie
# custom: ["https://example.com/donate"]
