version: 2

project_name: go_pi

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: go_pi
    main: ./cmd/gi
    binary: gi
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - examples/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: ejm
    repo: go_pi
  draft: false
  prerelease: false
  name_template: "{{.ProjectName}} {{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
