package agent

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/ejm/go_pi/pkg/ai"
)

// Compact summarizes the current conversation history using the LLM itself.
// It replaces all messages with a single summary message, preserving the
// system prompt. The optional instructions parameter lets the user guide
// what to focus on in the summary.
func (a *AgentLoop) Compact(ctx context.Context, instructions string) error {
	a.mu.Lock()
	msgs := cloneMessages(a.messages)
	model := a.model
	systemPrompt := a.systemPrompt
	maxTokens := a.maxTokens
	a.mu.Unlock()

	if len(msgs) == 0 {
		return fmt.Errorf("no messages to compact")
	}

	// Build a transcript of the conversation for the compaction prompt.
	var transcript strings.Builder
	for _, msg := range msgs {
		role := string(msg.Role)
		text := msg.GetText()
		if text != "" {
			transcript.WriteString(fmt.Sprintf("[%s]: %s\n\n", role, text))
		}
		for _, c := range msg.Content {
			switch c.Type {
			case ai.ContentTypeToolUse:
				transcript.WriteString(fmt.Sprintf("[tool_call]: %s\n", c.ToolName))
			case ai.ContentTypeToolResult:
				result := c.Content
				if len(result) > 500 {
					result = result[:500] + "..."
				}
				transcript.WriteString(fmt.Sprintf("[tool_result]: %s\n\n", result))
			}
		}
	}

	compactionPrompt := "Summarize the conversation so far, including key decisions, code changes made, files modified, and current state of the task. Be thorough but concise."
	if instructions != "" {
		compactionPrompt += "\n\nAdditional focus: " + instructions
	}
	compactionPrompt += "\n\n<conversation>\n" + transcript.String() + "</conversation>"

	// Send as a one-shot request using Stream and collect all text.
	compactionMsgs := []ai.Message{
		ai.NewTextMessage(ai.RoleUser, compactionPrompt),
	}

	req := ai.StreamRequest{
		Model:        model,
		SystemPrompt: systemPrompt,
		Messages:     compactionMsgs,
		MaxTokens:    maxTokens,
	}

	stream, err := a.provider.Stream(ctx, req)
	if err != nil {
		return fmt.Errorf("compaction stream: %w", err)
	}

	var summary strings.Builder
	for event := range stream {
		switch event.Type {
		case ai.EventTextDelta:
			summary.WriteString(event.Delta)
		case ai.EventError:
			return fmt.Errorf("compaction stream error: %w", event.Error)
		}
	}

	summaryText := summary.String()
	if summaryText == "" {
		return fmt.Errorf("compaction produced empty summary")
	}

	// Replace messages with a single user message containing the summary.
	compactedMsg := ai.NewTextMessage(ai.RoleUser,
		"[This is a summary of the conversation so far, generated by context compaction]\n\n"+summaryText,
	)

	a.mu.Lock()
	a.messages = []ai.Message{compactedMsg}
	a.mu.Unlock()

	a.emit(ctx, AgentEvent{
		Type:  EventCompaction,
		Delta: summaryText,
	})

	return nil
}

// maybeAutoCompact checks whether the context is approaching the limit and
// triggers automatic compaction if needed. It is called at the top of each
// iteration of the agent run loop.
func (a *AgentLoop) maybeAutoCompact(ctx context.Context) error {
	a.mu.Lock()
	contextWindow := a.contextWindow
	reserveTokens := a.reserveTokens
	lastInput := a.lastInputTokens
	a.mu.Unlock()

	// Auto-compaction disabled or no usage data yet.
	if contextWindow <= 0 || lastInput == 0 {
		return nil
	}

	threshold := contextWindow - reserveTokens
	if lastInput < threshold {
		return nil
	}

	log.Printf("agent: auto-compaction triggered (input_tokens=%d, threshold=%d)", lastInput, threshold)
	return a.autoCompact(ctx)
}

// autoCompact performs automatic compaction, summarizing older messages while
// preserving recent ones. It finds a safe cut point that never splits inside
// a tool-call/tool-result pair.
func (a *AgentLoop) autoCompact(ctx context.Context) error {
	a.mu.Lock()
	msgs := cloneMessages(a.messages)
	model := a.model
	systemPrompt := a.systemPrompt
	maxTokens := a.maxTokens
	keepRecent := a.keepRecentTokens
	a.mu.Unlock()

	if len(msgs) <= 1 {
		// Nothing meaningful to compact.
		return nil
	}

	// Find the cut point: everything before cutIdx gets summarized,
	// everything from cutIdx onward is kept.
	cutIdx := findSafeCutPoint(msgs, keepRecent)
	if cutIdx <= 0 {
		// Nothing old enough to summarize; fall back to full compaction.
		return a.Compact(ctx, "")
	}

	olderMsgs := msgs[:cutIdx]
	recentMsgs := msgs[cutIdx:]

	// Build transcript of older messages for summarization.
	var transcript strings.Builder
	for _, msg := range olderMsgs {
		role := string(msg.Role)
		text := msg.GetText()
		if text != "" {
			transcript.WriteString(fmt.Sprintf("[%s]: %s\n\n", role, text))
		}
		for _, c := range msg.Content {
			switch c.Type {
			case ai.ContentTypeToolUse:
				transcript.WriteString(fmt.Sprintf("[tool_call]: %s\n", c.ToolName))
			case ai.ContentTypeToolResult:
				result := c.Content
				if len(result) > 500 {
					result = result[:500] + "..."
				}
				transcript.WriteString(fmt.Sprintf("[tool_result]: %s\n\n", result))
			}
		}
	}

	compactionPrompt := "Summarize the conversation so far, including key decisions, code changes made, files modified, and current state of the task. Be thorough but concise. The conversation will continue after this summary, so preserve all context needed for ongoing work."
	compactionPrompt += "\n\n<conversation>\n" + transcript.String() + "</conversation>"

	req := ai.StreamRequest{
		Model:        model,
		SystemPrompt: systemPrompt,
		Messages:     []ai.Message{ai.NewTextMessage(ai.RoleUser, compactionPrompt)},
		MaxTokens:    maxTokens,
	}

	stream, err := a.provider.Stream(ctx, req)
	if err != nil {
		return fmt.Errorf("auto-compaction stream: %w", err)
	}

	var summary strings.Builder
	for event := range stream {
		switch event.Type {
		case ai.EventTextDelta:
			summary.WriteString(event.Delta)
		case ai.EventError:
			return fmt.Errorf("auto-compaction stream error: %w", event.Error)
		}
	}

	summaryText := summary.String()
	if summaryText == "" {
		return fmt.Errorf("auto-compaction produced empty summary")
	}

	// Replace older messages with summary, keep recent messages.
	compactedMsg := ai.NewTextMessage(ai.RoleUser,
		"[This is a summary of the conversation so far, generated by automatic context compaction]\n\n"+summaryText,
	)

	newMsgs := make([]ai.Message, 0, 1+len(recentMsgs))
	newMsgs = append(newMsgs, compactedMsg)
	newMsgs = append(newMsgs, recentMsgs...)

	a.mu.Lock()
	a.messages = newMsgs
	a.lastInputTokens = 0 // Reset so we don't re-trigger immediately.
	a.mu.Unlock()

	a.emit(ctx, AgentEvent{
		Type:  EventAutoCompaction,
		Delta: summaryText,
	})

	return nil
}

// findSafeCutPoint returns the index into msgs where the cut should happen.
// Messages before the cut are summarized; messages from the cut onward are kept.
// It ensures the cut never splits a tool_use/tool_result pair and preserves
// approximately keepRecentTokens worth of recent content.
//
// Token estimation uses ~4 characters per token as a heuristic.
func findSafeCutPoint(msgs []ai.Message, keepRecentTokens int) int {
	if keepRecentTokens <= 0 {
		keepRecentTokens = 4096
	}

	// Estimate tokens for each message (rough: 4 chars ≈ 1 token).
	charBudget := keepRecentTokens * 4

	// Walk backwards from the end, accumulating characters.
	accumulated := 0
	cutIdx := len(msgs)
	for i := len(msgs) - 1; i >= 0; i-- {
		msgChars := estimateMessageChars(msgs[i])
		if accumulated+msgChars > charBudget && cutIdx < len(msgs) {
			break
		}
		accumulated += msgChars
		cutIdx = i
	}

	// Adjust cut point to avoid splitting tool_use/tool_result pairs.
	// A tool_result must always follow its corresponding tool_use.
	// If the cut lands on a tool_result message, move the cut earlier
	// to include the tool_use as well.
	cutIdx = adjustCutForToolPairs(msgs, cutIdx)

	// Never summarize everything — keep at least one recent message.
	if cutIdx >= len(msgs) {
		cutIdx = len(msgs) - 1
	}

	return cutIdx
}

// adjustCutForToolPairs ensures the cut index doesn't land between a tool_use
// and its corresponding tool_result. If the message at cutIdx is a tool_result,
// move the cut earlier until we clear the tool_use/tool_result boundary.
func adjustCutForToolPairs(msgs []ai.Message, cutIdx int) int {
	if cutIdx <= 0 || cutIdx >= len(msgs) {
		return cutIdx
	}

	// Check if the message at cutIdx starts with a tool_result. If so,
	// we need to include the preceding tool_use (assistant message) in the
	// kept portion as well.
	for cutIdx > 0 {
		msg := msgs[cutIdx]
		hasToolResult := false
		for _, c := range msg.Content {
			if c.Type == ai.ContentTypeToolResult {
				hasToolResult = true
				break
			}
		}
		if !hasToolResult {
			break
		}
		// Move cut earlier to include the assistant message with tool_use.
		cutIdx--
	}

	return cutIdx
}

// SummarizeBranch generates a short summary of the given messages using the
// LLM. Unlike Compact, it does not modify the agent loop's state — it simply
// returns the summary string. This is used for branch summarization when the
// user switches branches via /fork or /tree.
func (a *AgentLoop) SummarizeBranch(ctx context.Context, msgs []ai.Message) (string, error) {
	if len(msgs) == 0 {
		return "", fmt.Errorf("no messages to summarize")
	}

	a.mu.Lock()
	model := a.model
	systemPrompt := a.systemPrompt
	a.mu.Unlock()

	var transcript strings.Builder
	for _, msg := range msgs {
		text := msg.GetText()
		if text != "" {
			transcript.WriteString(fmt.Sprintf("[%s]: %s\n\n", msg.Role, text))
		}
	}

	prompt := "Generate a one-line summary (max 80 characters) of this conversation branch. Focus on the main topic or outcome. Do not use quotes or prefixes.\n\n<conversation>\n" + transcript.String() + "</conversation>"

	req := ai.StreamRequest{
		Model:        model,
		SystemPrompt: systemPrompt,
		Messages:     []ai.Message{ai.NewTextMessage(ai.RoleUser, prompt)},
		MaxTokens:    200,
	}

	stream, err := a.provider.Stream(ctx, req)
	if err != nil {
		return "", fmt.Errorf("branch summary stream: %w", err)
	}

	var summary strings.Builder
	for event := range stream {
		switch event.Type {
		case ai.EventTextDelta:
			summary.WriteString(event.Delta)
		case ai.EventError:
			return "", fmt.Errorf("branch summary error: %w", event.Error)
		}
	}

	result := strings.TrimSpace(summary.String())
	if result == "" {
		return "", fmt.Errorf("branch summary produced empty result")
	}
	return result, nil
}

// estimateMessageChars returns a rough character count for a message.
func estimateMessageChars(msg ai.Message) int {
	total := 0
	for _, c := range msg.Content {
		switch c.Type {
		case ai.ContentTypeText:
			total += len(c.Text)
		case ai.ContentTypeThinking:
			total += len(c.Thinking)
		case ai.ContentTypeToolUse:
			total += len(c.ToolName) + 50 // name + rough input estimate
		case ai.ContentTypeToolResult:
			total += len(c.Content)
		}
	}
	return total
}
