package agent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strings"
	"unicode/utf8"

	"github.com/ejm/go_pi/pkg/ai"
)

var (
	errEmptySummary   = errors.New("compaction produced empty summary")
	errNoMessages     = errors.New("no messages to compact")
)

// minAutoCompactMessages is the minimum number of messages required before
// auto-compaction will trigger. A single massive tool result (or very few
// messages) can exceed the token threshold, but an LLM summarization call
// can't meaningfully compress so little context — it wastes tokens.
const minAutoCompactMessages = 4

// runCompaction streams a one-shot compaction request and returns the summary text.
// The caller constructs the prompt; this method handles the stream setup and
// text accumulation.
func (a *AgentLoop) runCompaction(ctx context.Context, prompt string) (string, error) {
	a.mu.Lock()
	model := a.model
	systemPrompt := a.systemPrompt
	maxTokens := a.maxTokens
	a.mu.Unlock()

	req := ai.StreamRequest{
		Model:        model,
		SystemPrompt: systemPrompt,
		Messages:     []ai.Message{ai.NewTextMessage(ai.RoleUser, prompt)},
		MaxTokens:    maxTokens,
	}

	stream, err := a.provider.Stream(ctx, req)
	if err != nil {
		return "", fmt.Errorf("compaction stream: %w", err)
	}

	var summary strings.Builder
	for event := range stream {
		switch event.Type {
		case ai.EventTextDelta:
			summary.WriteString(event.Delta)
		case ai.EventError:
			return "", fmt.Errorf("compaction stream error: %w", event.Error)
		}
	}

	text := summary.String()
	if text == "" {
		return "", errEmptySummary
	}
	return text, nil
}

// Compact summarizes the current conversation history using the LLM itself.
// It replaces all messages with a single summary message, preserving the
// system prompt. The optional instructions parameter lets the user guide
// what to focus on in the summary.
func (a *AgentLoop) Compact(ctx context.Context, instructions string) error {
	a.mu.Lock()
	msgs := cloneMessages(a.messages)
	a.mu.Unlock()

	if len(msgs) == 0 {
		return errNoMessages
	}

	transcript := buildTranscript(msgs)

	var promptBuilder strings.Builder
	promptBuilder.WriteString("Summarize the conversation so far, including key decisions, code changes made, files modified, and current state of the task. Be thorough but concise.")
	if instructions != "" {
		promptBuilder.WriteString("\n\nAdditional focus: ")
		promptBuilder.WriteString(instructions)
	}
	promptBuilder.WriteString("\n\n<conversation>\n")
	promptBuilder.WriteString(transcript)
	promptBuilder.WriteString("</conversation>")
	compactionPrompt := promptBuilder.String()

	summaryText, err := a.runCompaction(ctx, compactionPrompt)
	if err != nil {
		return fmt.Errorf("compact: %w", err)
	}

	compactedMsg := ai.NewTextMessage(ai.RoleUser,
		"[This is a summary of the conversation so far, generated by context compaction]\n\n"+summaryText,
	)

	a.mu.Lock()
	a.messages = []ai.Message{compactedMsg}
	a.mu.Unlock()

	a.emit(ctx, AgentEvent{
		Type:  EventCompaction,
		Delta: summaryText,
	})

	return nil
}

// maybeAutoCompact checks whether the context is approaching the limit and
// triggers automatic compaction if needed. It is called at the top of each
// iteration of the agent run loop.
func (a *AgentLoop) maybeAutoCompact(ctx context.Context) error {
	a.mu.Lock()
	contextWindow := a.contextWindow
	reserveTokens := a.reserveTokens
	lastInput := a.lastInputTokens
	msgCount := len(a.messages)
	a.mu.Unlock()

	// Auto-compaction disabled or no usage data yet.
	if contextWindow <= 0 || lastInput == 0 {
		return nil
	}

	threshold := contextWindow - reserveTokens
	if lastInput < threshold {
		return nil
	}

	// Don't trigger compaction when there are too few messages. A single
	// large tool result can exceed the token threshold, but summarizing
	// very few messages wastes an LLM call without meaningful reduction.
	if msgCount < minAutoCompactMessages {
		log.Printf("agent: auto-compaction skipped (messages=%d, min=%d)", msgCount, minAutoCompactMessages)
		return nil
	}

	log.Printf("agent: auto-compaction triggered (input_tokens=%d, threshold=%d)", lastInput, threshold)
	return a.autoCompact(ctx)
}

// autoCompact performs automatic compaction, summarizing older messages while
// preserving recent ones. It finds a safe cut point that never splits inside
// a tool-call/tool-result pair.
func (a *AgentLoop) autoCompact(ctx context.Context) error {
	a.mu.Lock()
	msgs := cloneMessages(a.messages)
	keepRecent := a.keepRecentTokens
	a.mu.Unlock()

	if len(msgs) <= 1 {
		// Nothing meaningful to compact.
		return nil
	}

	// Find the cut point: everything before cutIdx gets summarized,
	// everything from cutIdx onward is kept.
	cutIdx := findSafeCutPoint(msgs, keepRecent)
	if cutIdx <= 0 {
		// Nothing old enough to summarize; fall back to full compaction.
		return a.Compact(ctx, "")
	}

	olderMsgs := msgs[:cutIdx]
	recentMsgs := msgs[cutIdx:]

	transcript := buildTranscript(olderMsgs)

	var promptBuilder strings.Builder
	promptBuilder.WriteString("Summarize the conversation so far, including key decisions, code changes made, files modified, and current state of the task. Be thorough but concise. The conversation will continue after this summary, so preserve all context needed for ongoing work.")
	promptBuilder.WriteString("\n\n<conversation>\n")
	promptBuilder.WriteString(transcript)
	promptBuilder.WriteString("</conversation>")
	compactionPrompt := promptBuilder.String()

	summaryText, err := a.runCompaction(ctx, compactionPrompt)
	if err != nil {
		return fmt.Errorf("auto-compact: %w", err)
	}

	// Replace older messages with summary, keep recent messages.
	compactedMsg := ai.NewTextMessage(ai.RoleUser,
		"[This is a summary of the conversation so far, generated by automatic context compaction]\n\n"+summaryText,
	)

	newMsgs := make([]ai.Message, 0, 1+len(recentMsgs))
	newMsgs = append(newMsgs, compactedMsg)
	newMsgs = append(newMsgs, recentMsgs...)

	a.mu.Lock()
	a.messages = newMsgs
	a.lastInputTokens = 0 // Reset so we don't re-trigger immediately.
	a.mu.Unlock()

	a.emit(ctx, AgentEvent{
		Type:  EventAutoCompaction,
		Delta: summaryText,
	})

	return nil
}

// findSafeCutPoint returns the index into msgs where the cut should happen.
// Messages before the cut are summarized; messages from the cut onward are kept.
// It ensures the cut never splits a tool_use/tool_result pair and preserves
// approximately keepRecentTokens worth of recent content.
//
// Token estimation uses ~4 characters per token as a heuristic.
func findSafeCutPoint(msgs []ai.Message, keepRecentTokens int) int {
	if keepRecentTokens <= 0 {
		keepRecentTokens = 4096
	}

	// Estimate tokens for each message (rough: 4 chars ≈ 1 token).
	charBudget := keepRecentTokens * 4

	// Walk backwards from the end, accumulating characters.
	accumulated := 0
	cutIdx := len(msgs)
	for i := len(msgs) - 1; i >= 0; i-- {
		msgChars := estimateMessageChars(msgs[i])
		if accumulated+msgChars > charBudget && cutIdx < len(msgs) {
			break
		}
		accumulated += msgChars
		cutIdx = i
	}

	// Adjust cut point to avoid splitting tool_use/tool_result pairs.
	// A tool_result must always follow its corresponding tool_use.
	// If the cut lands on a tool_result message, move the cut earlier
	// to include the tool_use as well.
	cutIdx = adjustCutForToolPairs(msgs, cutIdx)

	// Never summarize everything — keep at least one recent message.
	if cutIdx >= len(msgs) {
		cutIdx = len(msgs) - 1
	}

	return cutIdx
}

// adjustCutForToolPairs ensures the cut index doesn't land between a tool_use
// and its corresponding tool_result. If the message at cutIdx is a tool_result,
// move the cut earlier until we clear the tool_use/tool_result boundary.
func adjustCutForToolPairs(msgs []ai.Message, cutIdx int) int {
	if cutIdx <= 0 || cutIdx >= len(msgs) {
		return cutIdx
	}

	// Check if the message at cutIdx starts with a tool_result. If so,
	// we need to include the preceding tool_use (assistant message) in the
	// kept portion as well.
	for cutIdx > 0 {
		msg := msgs[cutIdx]
		hasToolResult := false
		for _, c := range msg.Content {
			if c.Type == ai.ContentTypeToolResult {
				hasToolResult = true
				break
			}
		}
		if !hasToolResult {
			break
		}
		// Move cut earlier to include the assistant message with tool_use.
		cutIdx--
	}

	return cutIdx
}

// buildTranscript formats messages into a human-readable transcript string
// for use in compaction prompts.
func buildTranscript(msgs []ai.Message) string {
	var b strings.Builder
	for _, msg := range msgs {
		role := string(msg.Role)
		text := msg.GetText()
		if text != "" {
			fmt.Fprintf(&b, "[%s]: %s\n\n", role, text)
		}
		for _, c := range msg.Content {
			switch c.Type {
			case ai.ContentTypeToolUse:
				fmt.Fprintf(&b, "[tool_call]: %s\n", c.ToolName)
			case ai.ContentTypeToolResult:
				result := c.Content
				if len(result) > 500 {
					// Back up to a valid UTF-8 rune boundary to avoid
					// splitting multi-byte characters.
					truncLen := 500
					for truncLen > 0 && !utf8.RuneStart(result[truncLen]) {
						truncLen--
					}
					result = result[:truncLen] + "..."
				}
				fmt.Fprintf(&b, "[tool_result]: %s\n\n", result)
			}
		}
	}
	return b.String()
}

// estimateMessageChars returns a rough character count for a message.
func estimateMessageChars(msg ai.Message) int {
	total := 0
	for _, c := range msg.Content {
		switch c.Type {
		case ai.ContentTypeText:
			total += len(c.Text)
		case ai.ContentTypeThinking:
			total += len(c.Thinking)
		case ai.ContentTypeToolUse:
			total += len(c.ToolName) + 50 // name + rough input estimate
		case ai.ContentTypeToolResult:
			total += len(c.Content)
		}
	}
	return total
}
