package agent

import (
	"context"
	"fmt"
	"strings"

	"github.com/ejm/go_pi/pkg/ai"
)

// Compact summarizes the current conversation history using the LLM itself.
// It replaces all messages with a single summary message, preserving the
// system prompt. The optional instructions parameter lets the user guide
// what to focus on in the summary.
func (a *AgentLoop) Compact(ctx context.Context, instructions string) error {
	a.mu.Lock()
	msgs := cloneMessages(a.messages)
	model := a.model
	systemPrompt := a.systemPrompt
	maxTokens := a.maxTokens
	a.mu.Unlock()

	if len(msgs) == 0 {
		return fmt.Errorf("no messages to compact")
	}

	// Build a transcript of the conversation for the compaction prompt.
	var transcript strings.Builder
	for _, msg := range msgs {
		role := string(msg.Role)
		text := msg.GetText()
		if text != "" {
			transcript.WriteString(fmt.Sprintf("[%s]: %s\n\n", role, text))
		}
		for _, c := range msg.Content {
			switch c.Type {
			case ai.ContentTypeToolUse:
				transcript.WriteString(fmt.Sprintf("[tool_call]: %s\n", c.ToolName))
			case ai.ContentTypeToolResult:
				result := c.Content
				if len(result) > 500 {
					result = result[:500] + "..."
				}
				transcript.WriteString(fmt.Sprintf("[tool_result]: %s\n\n", result))
			}
		}
	}

	compactionPrompt := "Summarize the conversation so far, including key decisions, code changes made, files modified, and current state of the task. Be thorough but concise."
	if instructions != "" {
		compactionPrompt += "\n\nAdditional focus: " + instructions
	}
	compactionPrompt += "\n\n<conversation>\n" + transcript.String() + "</conversation>"

	// Send as a one-shot request using Stream and collect all text.
	compactionMsgs := []ai.Message{
		ai.NewTextMessage(ai.RoleUser, compactionPrompt),
	}

	req := ai.StreamRequest{
		Model:        model,
		SystemPrompt: systemPrompt,
		Messages:     compactionMsgs,
		MaxTokens:    maxTokens,
	}

	stream, err := a.provider.Stream(ctx, req)
	if err != nil {
		return fmt.Errorf("compaction stream: %w", err)
	}

	var summary strings.Builder
	for event := range stream {
		switch event.Type {
		case ai.EventTextDelta:
			summary.WriteString(event.Delta)
		case ai.EventError:
			return fmt.Errorf("compaction stream error: %w", event.Error)
		}
	}

	summaryText := summary.String()
	if summaryText == "" {
		return fmt.Errorf("compaction produced empty summary")
	}

	// Replace messages with a single user message containing the summary.
	compactedMsg := ai.NewTextMessage(ai.RoleUser,
		"[This is a summary of the conversation so far, generated by context compaction]\n\n"+summaryText,
	)

	a.mu.Lock()
	a.messages = []ai.Message{compactedMsg}
	a.mu.Unlock()

	// Emit a compaction event so the TUI knows what happened.
	a.emit(AgentEvent{
		Type:  EventCompaction,
		Delta: summaryText,
	})

	return nil
}
